import os
import py_compile

from sdc_parser import load_project
from sdc_compiler import AICompiler, get_provider
from sdc_codegen import generate_implementation


def _gen(example_dir, tmp_path):
    ir = load_project(example_dir).ir
    plan = AICompiler(get_provider("local")).plan_only(ir)
    files = generate_implementation(ir, plan.to_dict(), str(tmp_path))
    return ir, files


def test_generates_service_and_marker(example_dir, tmp_path):
    ir, files = _gen(example_dir, tmp_path)
    names = {os.path.basename(f) for f in files}
    assert {"service.py", "authorization_policy.json", "GENERATED.md"} <= names
    # deployment requires a container: a Dockerfile + container metadata
    assert {"Dockerfile", "container.json"} <= names


def test_service_is_valid_python(example_dir, tmp_path):
    _gen(example_dir, tmp_path)
    py_compile.compile(str(tmp_path / "service.py"), doraise=True)


def test_service_marked_generated(example_dir, tmp_path):
    _gen(example_dir, tmp_path)
    text = (tmp_path / "service.py").read_text()
    assert "GENERATED BY SDC" in text
    assert "DO NOT EDIT" in text


def test_no_hardcoded_secret(example_dir, tmp_path):
    import re

    _gen(example_dir, tmp_path)
    text = (tmp_path / "service.py").read_text()
    # secret must be read from env, not embedded as a non-empty literal
    assert 'Config().get("SDC_JWT_SECRET"' in text
    assert not re.search(r'SDC_JWT_SECRET["\']\s*[:=]\s*["\'][^"\']+["\']', text)


def test_sensitive_fields_embedded(example_dir, tmp_path):
    _gen(example_dir, tmp_path)
    text = (tmp_path / "service.py").read_text()
    assert "password" in text and "auth_token" in text  # in SENSITIVE map
