"""Python stdlib HTTP backend.

Generates a single, self-contained service file by inlining the SDC runtime
source (single source of truth) followed by an application section derived from
the IR: seed fixtures, sensitive-field projection, the compiled authorization
rules, behavior status mapping, and one handler per endpoint. The result runs
with ``python service.py`` and has zero third-party dependencies.
"""

from __future__ import annotations

import json
import os
from typing import Any

from sdc_ir import ApplicationIR
from sdc_runtime import runtime_source

from .base import CodeBackend


GENERATED_HEADER = '''\
# ---------------------------------------------------------------------------
# GENERATED BY SDC — DO NOT EDIT.
#
# This file is an intermediate build artifact. The authoritative source of
# truth is the Markdown specification set. This file is safe to delete and
# regenerate with `sdc compile` / `sdc build`.
# ---------------------------------------------------------------------------
'''


def _default_seed(ir: ApplicationIR) -> dict[str, list[dict]]:
    """Deterministic demo/verification fixtures derived from the entities.

    Two records in tenant ``t1`` and one in ``t2`` per entity, with ids like
    ``c1``, ``c2``, ``c3``. Sensitive fields get obviously-secret values so the
    verifier can assert they never appear in a response.
    """
    seed: dict[str, list[dict]] = {}
    for ent in ir.data.entities:
        prefix = ent.name[0].lower()
        rows = []
        for n, tenant in ((1, "t1"), (2, "t1"), (3, "t2")):
            rid = f"{prefix}{n}"
            row: dict[str, Any] = {}
            for f in ent.fields:
                if f.name == "id":
                    row["id"] = rid
                elif f.name == ent.tenant_field:
                    row[f.name] = tenant
                elif f.sensitive:
                    row[f.name] = f"secret-{f.name}-{rid}"
                else:
                    row[f.name] = f"{f.name}-{rid}"
            if "id" not in row:
                row["id"] = rid
            if ent.tenant_field and ent.tenant_field not in row:
                row[ent.tenant_field] = tenant
            rows.append(row)
        seed[ent.name] = rows
    return seed


APP_SECTION_TEMPLATE = '''

# === GENERATED APPLICATION ===============================================

APP = __APP__
META = __META__
AUTH_REQUIRED = __AUTH_REQUIRED__
BEHAVIOR = __BEHAVIOR__
AUTHZ_RULES = __AUTHZ_RULES__
SENSITIVE = __SENSITIVE__
TENANT_FIELD = __TENANT_FIELD__
OBS_FIELDS = __OBS_FIELDS__
DEFAULT_SEED = __DEFAULT_SEED__


def _telemetry() -> dict:
    # Runtime env overrides embedded metadata so a single artifact can carry
    # the specification/build identity into production telemetry.
    return {
        "specification_hash": os.environ.get("SDC_SPEC_HASH") or META.get("specification_hash"),
        "ir_hash": os.environ.get("SDC_IR_HASH") or META.get("ir_hash"),
        "build_id": os.environ.get("SDC_BUILD_ID") or META.get("build_id"),
        "artifact_version": APP.get("version"),
    }


def load_seed() -> dict:
    raw = os.environ.get("SDC_SEED_JSON")
    if raw:
        try:
            return json.loads(raw)
        except Exception:
            pass
    return DEFAULT_SEED


def authenticate(req):
    secret = Config().get("SDC_JWT_SECRET", "")
    token = req.bearer_token()
    if not token:
        if AUTH_REQUIRED:
            abort(BEHAVIOR.get("unauthenticated", 401), "authentication required")
        return Principal(subject="anonymous", tenant_id=None, role="anonymous", claims={})
    try:
        claims = jwt_verify(token, secret)
    except JWTError:
        if AUTH_REQUIRED:
            abort(BEHAVIOR.get("unauthenticated", 401), "invalid token")
        return Principal(subject="anonymous", tenant_id=None, role="anonymous", claims={})
    principal = Principal(
        subject=claims.get("sub", ""),
        tenant_id=claims.get("tenant_id"),
        role=claims.get("role", "user"),
        claims=claims,
    )
    req._tenant_id = principal.tenant_id
    return principal


def make_detail_handler(entity, param, store, policy):
    sensitive = SENSITIVE.get(entity, [])

    def handler(req):
        principal = authenticate(req)
        key = req.params.get(param)
        row = store.get(entity, key)
        if row is None:
            req._authz_decision = "not_found"
            abort(BEHAVIOR.get("not_found", 404), "not found")
        if AUTHZ_RULES:
            allowed, reason = policy.decide(principal, row)
        else:
            allowed, reason = True, "no-policy"
        req._authz_decision = reason
        if not allowed:
            abort(BEHAVIOR.get("unauthorized", 403), "forbidden")
        return Response(BEHAVIOR.get("success", 200), project_fields(row, sensitive))

    return handler


def make_collection_handler(entity, store, policy):
    sensitive = SENSITIVE.get(entity, [])
    tenant_field = TENANT_FIELD.get(entity)

    def handler(req):
        principal = authenticate(req)
        rows = store.list(entity, tenant_id=principal.tenant_id if tenant_field else None)
        visible = []
        for r in rows:
            if AUTHZ_RULES:
                allowed, _ = policy.decide(principal, r)
            else:
                allowed = True
            if allowed:
                visible.append(project_fields(r, sensitive))
        req._authz_decision = "list:tenant_scoped" if tenant_field else "list:all"
        return Response(BEHAVIOR.get("success", 200), visible)

    return handler


def build_app():
    config = Config()
    sensitive_all = sorted({f for fields in SENSITIVE.values() for f in fields})
    logger = StructuredLogger(sensitive_keys=sensitive_all, base={"service": APP.get("name")})
    metrics = Metrics()
    store = make_store(config, seed=load_seed())
    policy = Policy(AUTHZ_RULES)
    router = Router()
    app = App(
        router,
        config,
        logger,
        metrics,
        telemetry=_telemetry(),
        observability_fields=OBS_FIELDS,
    )
    app.install_builtin_routes()
__ROUTE_REGISTRATIONS__
    return app


def main():
    config = Config()
    app = build_app()
    host = config.get("HOST", "0.0.0.0")
    port = config.int("PORT", 8080)
    app.serve(host, port)


if __name__ == "__main__":
    main()
'''


class PythonHttpBackend(CodeBackend):
    name = "python-stdlib-http"

    def generate(self, ir, plan, out_dir, metadata=None):
        os.makedirs(out_dir, exist_ok=True)
        metadata = metadata or {}

        # Build embedded data structures.
        behavior = {r.condition: r.status for r in ir.behavior.rules}
        behavior.setdefault("unauthenticated", 401)
        behavior.setdefault("unauthorized", 403)
        behavior.setdefault("not_found", 404)
        behavior.setdefault("success", 200)

        sensitive = {e.name: e.sensitive_fields() for e in ir.data.entities}
        tenant_field = {e.name: e.tenant_field for e in ir.data.entities}
        authz_rules = [r.to_dict() for r in ir.authorization.rules]

        # Route registrations.
        reg_lines = []
        for ep in ir.api.endpoints:
            entity = ep.entity or (ir.data.entities[0].name if ir.data.entities else "Entity")
            if ep.path_params:
                param = ep.path_params[-1]
                reg_lines.append(
                    f"    router.add({ep.method!r}, {ep.path!r}, "
                    f"make_detail_handler({entity!r}, {param!r}, store, policy))"
                )
            else:
                reg_lines.append(
                    f"    router.add({ep.method!r}, {ep.path!r}, "
                    f"make_collection_handler({entity!r}, store, policy))"
                )
        route_registrations = "\n".join(reg_lines) if reg_lines else "    pass"

        # Embedded values are rendered as Python literals via repr() (json is
        # unsuitable because JSON null/true/false are not valid Python).
        app_section = APP_SECTION_TEMPLATE
        replacements = {
            "__APP__": repr({"name": ir.application.name, "version": ir.application.version}),
            "__META__": repr(
                {
                    "specification_hash": metadata.get("specification_hash"),
                    "ir_hash": metadata.get("ir_hash"),
                    "build_id": metadata.get("build_id"),
                }
            ),
            "__AUTH_REQUIRED__": "True" if ir.authentication.required else "False",
            "__BEHAVIOR__": repr(behavior),
            "__AUTHZ_RULES__": repr(authz_rules),
            "__SENSITIVE__": repr(sensitive),
            "__TENANT_FIELD__": repr(tenant_field),
            "__OBS_FIELDS__": repr(ir.observability.fields),
            "__DEFAULT_SEED__": repr(_default_seed(ir)),
        }
        for key, val in replacements.items():
            app_section = app_section.replace(key, val)
        app_section = app_section.replace("__ROUTE_REGISTRATIONS__", route_registrations)

        service_src = GENERATED_HEADER + runtime_source() + app_section

        written: list[str] = []

        service_path = os.path.join(out_dir, "service.py")
        with open(service_path, "w", encoding="utf-8") as fh:
            fh.write(service_src)
        written.append(service_path)

        # Compiled authorization policy artifact.
        policy_path = os.path.join(out_dir, "authorization_policy.json")
        with open(policy_path, "w", encoding="utf-8") as fh:
            json.dump(
                {"model": ir.authorization.model, "rules": authz_rules, "forbidden": ir.authorization.forbidden},
                fh,
                indent=2,
                sort_keys=True,
            )
        written.append(policy_path)

        # Deployment: Dockerfile + container metadata + healthcheck.
        if ir.deployment.container:
            dockerfile = os.path.join(out_dir, "Dockerfile")
            with open(dockerfile, "w", encoding="utf-8") as fh:
                fh.write(
                    "# GENERATED BY SDC — do not edit.\n"
                    "FROM python:3.11-slim\n"
                    "WORKDIR /app\n"
                    "COPY service.py /app/service.py\n"
                    "ENV PORT=8080 HOST=0.0.0.0\n"
                    "EXPOSE 8080\n"
                    "HEALTHCHECK --interval=10s --timeout=3s --retries=3 "
                    "CMD python -c \"import urllib.request,sys; "
                    "sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8080/healthz').status==200 else 1)\"\n"
                    'ENTRYPOINT ["python", "/app/service.py"]\n'
                )
            written.append(dockerfile)

            container_meta = os.path.join(out_dir, "container.json")
            with open(container_meta, "w", encoding="utf-8") as fh:
                json.dump(
                    {
                        "target": plan.get("target", ir.deployment.target),
                        "port": 8080,
                        "healthcheck": "/healthz",
                        "runtime_config": ["PORT", "HOST", "SDC_JWT_SECRET", "DATABASE_URL"],
                        "labels": {
                            "sdc.application": ir.application.name,
                            "sdc.version": ir.application.version,
                            "sdc.specification_hash": metadata.get("specification_hash"),
                            "sdc.build_id": metadata.get("build_id"),
                        },
                    },
                    fh,
                    indent=2,
                    sort_keys=True,
                )
            written.append(container_meta)

        # Generated marker.
        marker_path = os.path.join(out_dir, "GENERATED.md")
        with open(marker_path, "w", encoding="utf-8") as fh:
            fh.write(
                "# Generated implementation\n\n"
                "These files are generated from the Markdown specifications and are\n"
                "**not** the source of truth. They are safe to delete; run\n"
                "`sdc compile` to regenerate.\n\n"
                f"- backend: `{self.name}`\n"
                f"- language: `{plan.get('language')}`\n"
                f"- target: `{plan.get('target')}`\n"
            )
        written.append(marker_path)

        return written
