"""The AI compiler: IR -> validated plan -> generated implementation.

This is the ``AICompiler`` abstraction from the design. It is provider-neutral
(it holds an :class:`AIProvider`) and it never lets model output become an
artifact directly: the provider produces a *plan*, the plan is validated, and
only then is code generated by the code backend. The AI compiler does not
judge its own output — that is the verifier's job.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional

from sdc_ir import ApplicationIR
from sdc_ir.errors import CompilerError, GenerationError

from .providers import AIProvider, LocalDeterministicProvider
from .plan import ImplementationPlan, validate_plan


COMPILER_VERSION = "0.1.0"


@dataclass
class CompileResult:
    plan: ImplementationPlan
    generated_dir: str
    files: list[str]
    provider: str


class AICompiler:
    def __init__(self, provider: Optional[AIProvider] = None):
        self.provider = provider or LocalDeterministicProvider()

    def plan_only(
        self, application_ir: ApplicationIR, target: str = "", constraints: Optional[dict] = None
    ) -> ImplementationPlan:
        constraints = constraints or {}
        ir_dict = application_ir.to_dict()
        raw = self.provider.generate_plan(ir_dict, target, constraints)
        plan = ImplementationPlan.from_dict(raw)
        errors = validate_plan(plan)
        if errors:
            raise CompilerError(
                "Implementation plan failed validation",
                why="; ".join(e.what for e in errors),
                component="ai-compiler",
                details=[e.what for e in errors],
            )
        return plan

    def compile(
        self,
        application_ir: ApplicationIR,
        target: str = "",
        constraints: Optional[dict] = None,
        out_dir: str = "build/generated",
    ) -> CompileResult:
        plan = self.plan_only(application_ir, target, constraints)

        # Import here to keep the dependency direction explicit and avoid a
        # hard import at module load if codegen is not installed.
        try:
            from sdc_codegen import generate_implementation
        except Exception as exc:  # pragma: no cover
            raise GenerationError(
                "Code generator unavailable", why=str(exc), component="codegen"
            ) from exc

        try:
            files = generate_implementation(application_ir, plan.to_dict(), out_dir)
        except Exception as exc:
            raise GenerationError(
                "Code generation failed",
                why=str(exc),
                component="codegen",
            ) from exc

        return CompileResult(
            plan=plan, generated_dir=out_dir, files=files, provider=self.provider.name
        )
